### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/docs.pact.io#112]
When running `scripts/build.sh` there are a number of broken links reported.

```
Exhaustive list of all broken links found:

- On source page path = /getting_started/provider_verification:
   -> linking to /implementation_guides/jvm/provider_menu
   -> linking to /implementation_guides/

- On source page path = /pact_broker:
   -> linking to /pact_broker/configuration#running-the-broker-behind-a-reverse-proxy (resolved as: /pact_broker/configuration)

- On source page path = /pact_broker/advanced_topics/api_docs:
   -> linking to ./publish_pact (resolved as: /pact_broker/advanced_topics/publish_pact)
   -> linking to ./publish_verification_result (resolved as: /pact_broker/advanced_topics/publish_verification_result)
   -> linking to ./webhooks (resolved as: /pact_broker/advanced_topics/webhooks)
   -> linking to ./pact_diff (resolved as: /pact_broker/advanced_topics/pact_diff)

- On source page path = /pact_broker/webhooks/debugging_webhooks:
   -> linking to /pact_broker/configuration#webhook-whitelists (resolved as: /pact_broker/configuration)

- On source page path = /recipes:
   -> linking to graphql (resolved as: /graphql)
   -> linking to apigateway (resolved as: /apigateway)
   -> linking to lambdahttp (resolved as: /lambdahttp)
   -> linking to cypress (resolved as: /cypress)
   -> linking to kafka (resolved as: /kafka)
```

**Comment by mefellows** [comment]
I saw this the other day too. I think we should consider breaking the build if this finds errors.

**Comment by YOU54F** [comment]
I think I have broken these in the following PR https://github.com/pact-foundation/docs.pact.io/pull/110/files

which is odd, as the issue was reported that the link was resolving to https://docs.pact.io/recipes/recipes/kafka which is a dead link. (dupe recipes)

Even odder, is that I forgot to change one of them 🤦🏾 [Lambda/FaaS (Asynchronous)](https://docs.pact.io/recipes/lambdaasync) and that one works fine. 

> - On source page path = /recipes:
   -> linking to graphql (resolved as: /graphql)
   -> linking to apigateway (resolved as: /apigateway)
   -> linking to lambdahttp (resolved as: /lambdahttp)
   -> linking to cypress (resolved as: /cypress)
   -> linking to kafka (resolved as: /kafka)
   
  
  - Maybe we should revert [my update to above links - PR](https://github.com/pact-foundation/docs.pact.io/pull/110/files) and check?
- I'm happy to pick up updating the other links

**Comment by YOU54F** [comment]
It is the opposite way round again! 🤷🏾‍♂️ 

https://docs.pact.io/recipes/

The [Lambda/FaaS (Asynchronous)](https://docs.pact.io/recipes/recipes/lambdaasync) link is resolving to the wrong place, but the ones identified as broken are now working again

eg 

[Cypress](https://docs.pact.io/recipes/cypress)

Will put this on my list of things to look at 👍🏾

**Comment by bethesque** [comment]
Yeah, there was an issue with paths ending in `/readme` that I've fixed now, that may have been related.
